plugins {
    id 'com.android.application'
}

android {
    namespace 'com.xplc.capture'
    compileSdk 35

    defaultConfig {
        applicationId 'com.xplc.capture'
        minSdk 29
        targetSdk 35
        versionCode 3
        versionName '1.2.0'
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
}
